global:
  nameOverride:

# 
image:
  name: ghcr.io/gepaplexx/oauth-group-sync-operator
  tag: latest

replicas: 1

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

  