apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "Chart.name" . }}
  labels:
    {{- include "Chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "Chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "Chart.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "Chart.name" . }}
      containers:
      - name: sync
        image: {{ include "Chart.imageName" . }}
{{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
{{- end }}