kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "Chart.name" . }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "Chart.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "Chart.name" . }}
    namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin